<?php

/**
 * Implementation of hook_geonode_plugin().
 */
function geonode_google_geonode_plugin() {
  $args = func_get_args();
  $op = array_shift($args);

  switch ($op) {
    case 'name':
      return 'google';
      break;

    case 'title':
      return 'Google Maps';
      break;

    case 'settings_form':
      $form = array();

      $form['key'] = array(
        '#type' => 'textfield',
        '#title' => t('Google Maps API key'),
        '#default_value' => variable_get('geonode_google_key', ''),
      );

      $form['map_type'] = array(
        '#type' => 'select',
        '#title' => t('Map type'),
        '#default_value' => variable_get('geonode_google_map_type', 'ROADMAP'),
        '#options' => array(
          'ROADMAP' => t('Roadmap'),
          'SATELLITE' => t('Satellite'),
          'HYBRID' => t('Hybryd'),
          'TERRAIN' => t('Terrain'),
        ),
      );

      $form['zoom'] = array(
        '#type' => 'textfield',
        '#title' => t('Default zoom'),
        '#default_value' => variable_get('geonode_google_zoom', 18),
      );

      $form['imagery'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable Aerial Perspective Imagery'),
        '#default_value' => variable_get('geonode_google_imagery', 0),
        '#description' => t('The Google Maps API supports special 45° imagery for certain locations. This high-resolution imagery provides perspective views towards each of the cardinal direction (North, South, East, West). Works only with the Hibrid and Sattesite maps.'),
      );

      $form['imagery_angle'] = array(
        '#type' => 'textfield',
        '#title' => t('Imagery angle (°)'),
        '#default_value' => variable_get('geonode_google_imagery_angle', 45),
      );

      return $form;
      break;

    case 'settings_form_submit':
      $post = array_shift($args);
      if ($post) {
        variable_set('geonode_google_key', $post['key']);
        variable_set('geonode_google_map_type', $post['map_type']);
        variable_set('geonode_google_zoom', $post['zoom']);
        variable_set('geonode_google_imagery', $post['imagery']);
        variable_set('geonode_google_imagery_angle', $post['imagery_angle']);
      }
      break;

    case 'location':
      $lat = array_shift($args);
      $lon = array_shift($args);
      drupal_add_js('https://maps.googleapis.com/maps/api/js?v=3&key=' . variable_get('geonode_google_key', '') . '&sensor=false', 'external');
      drupal_add_js("
      function set_location(loc) {
        jQuery('input[name=\"lat\"]').val(loc.lat());
        jQuery('input[name=\"lon\"]').val(loc.lng());
      }
      function initialize() {
        var myLatLon = new google.maps.LatLng({$lat}, {$lon});
        var mapOptions = {
          zoom: " . variable_get('geonode_google_zoom', 10) . ",
          center: myLatLon,
          mapTypeId: google.maps.MapTypeId." . variable_get('geonode_google_map_type', 'ROADMAP') . "
        };
        var map = new google.maps.Map(document.getElementById('google-container'), mapOptions);
        var marker = new google.maps.Marker({
          position: myLatLon,
          map: map,
          draggable:true
        });
        google.maps.event.addListener(marker, 'dragend', set_location);

        google.maps.event.addListener(map, 'click',
          function(event) {
            marker.setPosition(event.latLng);
            set_location(event.latLng);
          }
        );

        ".(variable_get('geonode_google_imagery', 0)?"map.setTilt(45);\n map.setHeading(".variable_get('geonode_google_imagery_angle', 45).");":'')."
      }
      google.maps.event.addDomListener(window, 'load', initialize);
      ", 'inline');

      $output = '<div id="google-container" style="height:400px;position:relative;width:100%;margin:0px;"></div>';
      return $output;
      break;

    case 'render':
      $markers = array_shift($args);
      $lat = $lon = 0;

      drupal_add_js('https://maps.googleapis.com/maps/api/js?v=3&key=' . variable_get('geonode_google_key', '') . '&sensor=false', 'external');

      $script = "
        function initialize() {
          var map = new google.maps.Map(document.getElementById('google-container'), {
            zoom: " . variable_get('geonode_google_zoom', 10) . ",
            mapTypeId: google.maps.MapTypeId." . variable_get('geonode_google_map_type', 'ROADMAP') . "
          });\n\n";

      foreach ($markers as $nid => $marker) {
        $lat = $marker['latitude'];
        $lon = $marker['longitude'];
        $marker['title'] = str_replace ("'", "\'", $marker['title']);
        $script .= "
          var marker_{$nid} = new google.maps.Marker({
            position: new google.maps.LatLng({$marker['latitude']}, {$marker['longitude']}),
            map: map
          });
          var info_{$nid} = new google.maps.InfoWindow({
            content: '{$marker['title']}'
          });
          google.maps.event.addListener(marker_{$nid}, 'click',
            function() {
              info_{$nid}.open(map, marker_{$nid});
            }
          );
        \n\n";
      }

      $script .= "
          map.setCenter(new google.maps.LatLng({$lat}, {$lon}));
          ".(variable_get('geonode_google_imagery', 0)?"map.setTilt(45);\n map.setHeading(".variable_get('geonode_google_imagery_angle', 45).");":'')."
        }
        google.maps.event.addDomListener(window, 'load', initialize);";

      drupal_add_js($script, 'inline');
      $output = '<div id="google-container" style="height:400px;position:relative;width:100%;margin:0px;"></div>';
      return $output;
      break;
  }
}